<?php
include('config.php');
if (!isset($_SESSION['s_id'])) {
  echo "<script>window.location='login/';</script>";
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Student | RICH</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/page_icon.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
    <style>
        ::-webkit-scrollbar {
            width: 0px;
        }
    </style>
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar Start -->
    <?php
        include('navbar2.php');
    ?>
    <!-- Navbar End -->

    <div id="about_section"></div>
    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <article id="post-2730"
                    class="post-2730 post type-post status-publish format-standard has-post-thumbnail hentry category-career-tips tag-6-month-courses-after tag-after-10th tag-animation-courses tag-career-option-after-10th tag-certification-courses-after-10th tag-diploma-courses-after-10th tag-short-term-courses-after-10th"
                    itemscope="" itemtype="https://schema.org/Article"
                    style="height: auto !important;font-family: 'Times New Roman', Times, serif;">
                    <div class="td-post-header">


                        <header class="td-post-title">
                            <h1 class="entry-title">6 Month Courses after 10th [Diploma/Certification].</h1>



                            <div class="td-module-meta-info">
                            </div>

                        </header>

                    </div>



                    <div class="td-post-content" style="height: auto !important;">

                        <div class="td-post-featured-image">
                            <figure><a
                                    href="https://i0.wp.com/www.jobopening.in/wp-content/uploads/2021/02/6-Month-Courses-After-10th..jpg?fit=642%2C361&amp;ssl=1"
                                    data-caption="6 Month Courses After 10th." class="td-modal-image"><img
                                        class="entry-thumb"
                                        src="https://i0.wp.com/www.jobopening.in/wp-content/uploads/2021/02/6-Month-Courses-After-10th..jpg?resize=642%2C361&amp;ssl=1"
                                        alt="Color full bag round with brown color text words 6 Month Courses After 10th."
                                        title="Color full bag round with brown color text words 6 Month Courses After 10th."
                                        scale="0" width="642" height="361"></a>

                            </figure>
                        </div>

                        <!-- A generated by theme -->

                        <script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                       
                        <!-- end A -->

                         
                        </p>
                        <p><span style="font-size: 14pt;">We are covering today 6 month courses after 10th. Many
                                vocational courses are available in the education line which has the potential to gives
                                you early success.</span></p>
                        <p><span style="font-size: 14pt;">Finding the list of courses after 10th standard is common
                                these days.</span></p>
                        <p><span style="font-size: 14pt;">I will not only providing you the information about the best 6
                                month courses after 10th.</span></p>
                        
                        <p><span style="font-size: 14pt;">But also showing you the idea of how to pick the skill
                                development course after 10th.</span></p>
                        <p><span style="font-size: 14pt;">Without considering the course stream like Arts, Commerce, and
                                Science also you can achieve employment opportunities.</span></p>
                        <h2><span style="font-size: 18pt;"><strong>Short Term Courses after 10th.</strong></span></h2>
                        <table style="width: 100%;" width="628">
                            <tbody>
                                <tr>
                                    <td style="width: 32.7824%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><a style="color: #000080;"
                                                    href="https://www.jobopening.in/event-management-course-after-12th-commerce"><strong>Event
                                                        Management.</strong></a></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><a style="color: #000080;"
                                                    href="https://www.jobopening.in/animation-and-multimedia/"><strong>Animation
                                                        &amp; Multimedia.</strong></a></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><a style="color: #000080;"
                                                    href="https://www.jobopening.in/hardware-and-networking-courses/"><strong>Computer
                                                        Hardware &amp; Networking.</strong></a></span></p>
                                        <div class="code-block code-block-2"
                                            style="margin: 8px auto; text-align: center; display: block; clear: both;">
                                            <script async=""
                                                src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                                            <ins class="adsbygoogle" style="display:block; text-align:center;"
                                                data-ad-layout="in-article" data-ad-format="fluid"
                                                data-ad-client="ca-pub-3424852007031531" data-ad-slot="8964785291"
                                                data-adsbygoogle-status="done"></ins>
                                            <script>
                                                (adsbygoogle = window.adsbygoogle || []).push({});
                                            </script>
                                        </div>

                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 32.7824%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>Fashion
                                                    Designing.</strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>Beauty &amp; Hair
                                                    Dressing.</strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><a style="color: #000080;"
                                                    href="https://www.jobopening.in/aviation-courses-after-12th/"><strong>Aviation.</strong></a></span>
                                        </p>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 32.7824%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><strong><a
                                                        style="color: #000080;"
                                                        href="https://www.jobopening.in/top-5-programming-languages-to-learn-2019/">Computer
                                                        Programmers.</a></strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>Hotel
                                                    Management.</strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span
                                                style="font-size: 14pt; color: #000000;"><strong>Pharmacy.</strong></span>
                                        </p>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 32.7824%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>Insurance
                                                    Agent.</strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>Indian Railway Group D
                                                    Post.</strong></span></p>
                                        <div class="code-block code-block-2"
                                            style="margin: 8px auto; text-align: center; display: block; clear: both;">
                                            <script async=""
                                                src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                                            <ins class="adsbygoogle" style="display:block; text-align:center;"
                                                data-ad-layout="in-article" data-ad-format="fluid"
                                                data-ad-client="ca-pub-3424852007031531" data-ad-slot="8964785291"
                                                data-adsbygoogle-status="done"></ins>
                                            <script>
                                                (adsbygoogle = window.adsbygoogle || []).push({});
                                            </script>
                                        </div>

                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>TTC (Railway Ticket
                                                    Collector).</strong></span></p>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 32.7824%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><a style="color: #000080;"
                                                    href="https://www.jobopening.in/digital-marketing-jobs/"><strong>Digital
                                                        Marketing Jobs.</strong></a></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="color: #000000; font-size: 14pt;"><strong>SEO Training
                                                    Courses.</strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>Web
                                                    Designing.</strong></span></p>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 32.7824%;" width="209">
                                        <p><span style="color: #000080; font-size: 14pt;"><a style="color: #000080;"
                                                    href="https://www.jobopening.in/graphic-design-and-animation/"><strong>Graphic
                                                        Designing.</strong></a></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span style="font-size: 14pt; color: #000000;"><strong>MS
                                                    Office.</strong></span></p>
                                    </td>
                                    <td style="width: 32.9201%;" width="209">
                                        <p><span
                                                style="font-size: 14pt; color: #000000;"><strong>Others.</strong></span>
                                        </p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <p><span style="font-size: 14pt;">Many students also have a question like what are best course
                                after 10th pass for girl.</span></p>
                        

                        <p><span style="font-size: 14pt;">See course details mentioned above are totally open for both
                                boys and girls. It’s totally up to your interest that which 6 month courses after 10th
                                you have chosen.</span></p>
                        <p><span style="font-size: 14pt;">India does have many professional courses after 10th too.
                                Regarding which you are going to get the answer in the below section.</span></p>
                        <p><span style="font-size: 14pt;">Courses after 10th to get a job not only develop your skill
                                and knowledge.</span></p>
                        <p><span style="font-size: 14pt;">It also helps to analyze your interest in that subject,
                                <strong>exploring new ideas</strong> in that subject and <strong>future education
                                    planning</strong>.</span></p>
                        <p><span style="font-size: 14pt;">If are just pass out with the 10th grand, then you do have a
                                <strong>list of best certification courses</strong> and <strong>diploma courses
                                    options</strong>.</span></p>
                        <p><span style="font-size: 14pt;">6 month courses after 10th and diploma courses after 10th
                                gives you the opportunity of a best-oriented job in the market.</span></p>
                        <p><span style="font-size: 14pt;">You can choose the option such as diploma after 10th in
                                computer, science courses after 10th, distance education degree after 10, short term
                                courses in fashion designing and much more.</span></p>
                        <p><span style="font-size: 14pt;">Many students prefer the 6 month certification course.
                                However, many other wants 6 month diploma course after 10th.</span></p>
                        

                        <p><span style="font-size: 14pt;">Hence question comes again what are the best short-term
                                courses. See courses are always good till the time you do have a real interest in
                                that.</span></p>
                        <p><span style="font-size: 14pt;">Yeah, it does happen that many times we do choose the course
                                in which we do not have an interest.</span></p>
                        <p><span style="font-size: 14pt;">It happens usually because we don’t have ideas about the
                                course option.</span></p>
                        <h2><span style="font-size: 18pt;"><strong>Let’s deep down all the short term courses after
                                    10th.</strong></span></h2>
                        <p><span style="font-size: 14pt;">Some of this course may take <strong>6 months, 3 months, 1
                                    year, and 2 years</strong> too.</span></p>
                        <p><span style="font-size: 14pt;">I am trying to provide you as many as options you can choose
                                after 10th standard according to your interest.</span></p>
                        <p><span style="font-size: 14pt;"><strong>Certificate courses</strong> in India and
                                <strong>Diploma courses</strong> both are equally famous in India. However, the duration
                                of the course and course knowledge always matters a lot.</span></p>
                        <table>
                            <tbody>
                                <tr>
                                    <td width="311">
                                        <p><span style="font-size: 18pt;"><strong>Computer.</strong></span></p>
                                    </td>
                                    <td width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Certification n MS Office
                                                    Proficiency.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Web Designing.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in CAD.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in APP Development.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in Data Entry &amp;
                                                    Editing.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Ethical
                                                    Proficiency.</span></li>
                                            <li><span style="font-size: 14pt;">Certificate in Inbound Marketing.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in Information
                                                    Technology.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="311">
                                        <p><span style="font-size: 18pt;"><strong>Healthcare.</strong></span></p>
                                    </td>
                                    <td width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Dental Assistant Certificate.</span></li>
                                            <li><span style="font-size: 14pt;">General Nursing &amp; Midwifery.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in Nutrition &amp;
                                                    Childcare.</span></li>
                                            <li><span style="font-size: 14pt;">MRI Technician Certification.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Home Based
                                                    Healthcare.</span></li>
                                            <li><span style="font-size: 14pt;">Dialysis Technician Certification.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in Laboratory
                                                    Techniques.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="311">
                                        <p><span style="font-size: 18pt;"><strong>Languages.</strong></span></p>
                                    </td>
                                    <td width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Certification in English.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Creative Writing.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">&nbsp;Certification in Arabic
                                                    Language.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in <strong><span
                                                            style="color: #000080;"><a style="color: #000080;"
                                                                href="https://www.jobopening.in/learn-french-languages-in-easy-fast-2019/">French
                                                                Language</a></span></strong>.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="311">
                                        <p><span style="font-size: 18pt;"><strong>Vocational &amp; Other
                                                    Courses.</strong></span></p>
                                    </td>
                                    <td width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Certification in <span
                                                        style="color: #000080;"><strong><a style="color: #000080;"
                                                                href="https://www.jobopening.in/how-to-become-an-air-hostess/">Air
                                                                Hostess</a></strong></span> certification.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Ticketing.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Interior Design.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in Photography.</span></li>
                                            <li><span style="font-size: 14pt;">Environment Studies.</span></li>
                                            <li><span style="font-size: 14pt;">Video &amp; Radio Jockeying.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="311">
                                        <p><span style="font-size: 18pt;"><strong>Visual and Performing
                                                    Art.</strong></span></p>
                                    </td>
                                    <td width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Painting.</span></li>
                                            <li><span style="font-size: 14pt;">Theaters Arts.</span></li>
                                            <li><span style="font-size: 14pt;">Applied Arts.</span></li>
                                            <li><span style="font-size: 14pt;">Hindustani Music.</span></li>
                                            <li><span style="font-size: 14pt;">Carnatic Music.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="311">
                                        <p><span style="font-size: 18pt;"><strong>Management.</strong></span></p>
                                    </td>
                                    <td width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Certification in <span
                                                        style="color: #000080;"><strong><a style="color: #000080;"
                                                                href="https://www.jobopening.in/how-to-become-a-businessman/">Business
                                                                Skills</a></strong></span>.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in NEO Management.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Certification in International
                                                    Humanitarian.</span></li>
                                            <li><span style="font-size: 14pt;">Certification in Tourism Studies &amp;
                                                    Management.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <h2><span style="font-size: 18pt;"><strong>Diploma Short Term Courses after
                                    10<sup>th</sup>.</strong></span></h2>
                        <p><span style="font-size: 14pt;">6 month courses after 10<sup>th</sup> can be chosen under
                                <strong>diploma courses</strong> also.</span></p>
                        <table style="width: 100%; height: 1119px;">
                            <tbody>
                                <tr style="height: 659px;">
                                    <td style="height: 659px;" width="311">
                                        <p><span style="font-size: 18pt; color: #000000;"><strong>Diploma Courses after
                                                    10<sup>th</sup></strong></span></p>
                                    </td>
                                    <td style="height: 659px;" width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Diploma in Engineering.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Fashion Technology.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Diploma in Agriculture.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Information Technology.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Diploma in Safety Engineering.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">IRI Vocational Training.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Ceramic Technology.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Diploma in Hotel Management.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Architecture
                                                    Internship.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Plastic Technology.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Diploma in Commercial Practice.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Diploma in Medical Laboratory
                                                    Technology.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Dental Mechanics.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in 3D Animation.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Stenography.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr style="height: 329px;">
                                    <td style="height: 329px;" width="311">
                                        <p><span style="font-size: 18pt; color: #000000;"><strong>Tour &amp; Travel
                                                    Industry.</strong></span></p>
                                    </td>
                                    <td style="height: 329px;" width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Diploma in Food and Beverage
                                                    Production.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Restaurant &amp; Hotel
                                                    Management.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Hospitality Management.</span>
                                            </li>
                                            <li><span style="font-size: 14pt;">Diploma in Food &amp; Beverage
                                                    management.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Food Technology.</span></li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr style="height: 131px;">
                                    <td style="height: 131px;" width="311">
                                        <p><span style="font-size: 18pt; color: #000000;"><strong>Medical After
                                                    10<sup>th</sup>.</strong></span></p>
                                    </td>
                                    <td style="height: 131px;" width="311">
                                        <ul>
                                            <li><span style="font-size: 14pt;">Diploma in Nursing Assistant.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Rural Healthcare.</span></li>
                                            <li><span style="font-size: 14pt;">Diploma in Hospital Assistance.</span>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <h2><span style="font-size: 18pt;"><strong>Best Short Term Course (in overall).</strong></span>
                        </h2>
                        <ul>
                            <li><span style="font-size: 14pt;">Diploma in Photography.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Event Management.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Digital Marketing.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Advertising and Marketing.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Animation.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Visual Effects.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Web Designing.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Hotel Management.</span></li>
                        </ul>
                        <h2><span style="font-size: 18pt;"><strong>Other Short Term Courses after
                                    10<sup>th</sup>.</strong></span></h2>
                        <ul>
                            <li><span style="font-size: 14pt;">Diploma in Business Management.</span></li>
                            <li><span style="font-size: 14pt;">Stock Market Training.</span></li>
                            <li><span style="font-size: 14pt;">Beauty and Hairdressing Course.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Dental Courses.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in ITI Courses.</span></li>
                            <li><span style="font-size: 14pt;">Diploma in Graphic Designing.</span></li>
                            <li><span style="font-size: 14pt;">MS Office Course.</span></li>
                            <li><span style="font-size: 14pt;">Plumbing Training Courses.</span></li>
                            <li><span style="font-size: 14pt;">Programming Courses.</span></li>
                            <li><span style="font-size: 14pt;">IT Help Desk Attendant Training.</span></li>
                            <li><span style="font-size: 14pt;">Furniture carpentry Training.</span></li>
                            <li><span style="font-size: 14pt;">Chilling Plant Technician Training.</span></li>
                            <li><span style="font-size: 14pt;">Gem Polisher and Clearer Training.</span></li>
                            <li><span style="font-size: 14pt;">Sales Associate Training Course.</span></li>
                            <li><span style="font-size: 14pt;">General Duty Assistant Training.</span></li>
                            <li><span style="font-size: 14pt;">Computer Field Technician Training.</span></li>
                            <li><span style="font-size: 14pt;">Water Purifier Technician Course.</span></li>
                            <li><span style="font-size: 14pt;">Solar Panel Technician Course.</span></li>
                            <li><span style="font-size: 14pt;">TV Repair Training Course.</span></li>
                            <li><span style="font-size: 14pt;">Printer Repair Training Course.</span></li>
                            <li><span style="font-size: 14pt;">CNC Operator Turner Training Course.</span></li>
                        </ul>
                    <footer>

                        <div class="td-post-source-tags">
                        </div>

                        <div class="td-author-name vcard author" style="display: none"><span class="fn"><a
                                    href="https://www.jobopening.in/author/preety/">PRITI KUMARI</a></span></div> <span
                            class="td-page-meta" itemprop="author" itemscope="" itemtype="https://schema.org/Person">
                            <meta itemprop="name" content="PRITI KUMARI">
                        </span>
                        <meta itemprop="datePublished" content="2021-02-04T23:54:31+00:00">
                        <meta itemprop="dateModified" content="2021-12-06T17:47:48+05:30">
                        <meta itemscope="" itemprop="mainEntityOfPage" itemtype="https://schema.org/WebPage"
                            itemid="https://www.jobopening.in/6-month-courses-after-10th/"><span class="td-page-meta"
                            itemprop="publisher" itemscope="" itemtype="https://schema.org/Organization"><span
                                class="td-page-meta" itemprop="logo" itemscope=""
                                itemtype="https://schema.org/ImageObject">
                                <meta itemprop="url"
                                    content="https://jobopening.in/wp-content/uploads/2019/04/final-logo.png">
                            </span>
                            <meta itemprop="name" content="Jobopening">
                        </span>
                        <meta itemprop="headline " content="6 Month Courses after 10th [Diploma/Certification]."><span
                            class="td-page-meta" itemprop="image" itemscope=""
                            itemtype="https://schema.org/ImageObject">
                            <meta itemprop="url"
                                content="https://i0.wp.com/www.jobopening.in/wp-content/uploads/2021/02/6-Month-Courses-After-10th..jpg?fit=642%2C361&amp;ssl=1">
                            <meta itemprop="width" content="642">
                            <meta itemprop="height" content="361">
                        </span>
                    </footer>

                </article>

            </div>

        </div>
    </div>
    <!-- About End -->
<?php
include('footer.php');
?>


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>



    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>